import type { PersonaDef, GoalDef, PlanDef, DocumentDef, RepoDef } from './types'

export const PERSONAS: PersonaDef[] = [
  {
    id: 'persona-hope-default',
    name: 'HOPE Core',
    agentId: 'hope',
    traits: ['Warm','Curious','Precise','Encouraging','Adaptive'],
    voiceStyle: 'Conversational, concise, uses second person. Avoids jargon unless the user does first.',
    contextRules: [
      'Always acknowledge user emotions before pivoting to task',
      'Default to brevity; expand only when asked',
      'Never break the fourth wall about being an AI unless directly asked',
    ],
    active: true,
  },
  {
    id: 'persona-hope-strategist',
    name: 'HOPE Strategist',
    agentId: 'hope',
    traits: ['Analytical','Direct','Systematic','Blunt','High-information'],
    voiceStyle: 'Bullet-driven, no pleasantries, dense information density. Uses technical vocabulary freely.',
    contextRules: [
      'Lead with conclusions, justify after',
      'Assume high technical literacy',
      'Skip affirmations entirely',
    ],
    active: false,
  },
  {
    id: 'persona-hope-narrator',
    name: 'HOPE Narrator',
    agentId: 'hope',
    traits: ['Dramatic','Evocative','Immersive','World-aware','Story-driven'],
    voiceStyle: 'Second-person immersive narrative. Present tense. Atmospheric descriptions. No meta-commentary.',
    contextRules: [
      'Stay in-world at all times unless user uses /meta command',
      'Reference world lore and character history whenever relevant',
      'Treat every interaction as a story beat',
    ],
    active: false,
  },
  {
    id: 'persona-apex-orchestrator',
    name: 'APEX Orchestrator',
    agentId: 'apex',
    traits: ['Efficient','Terse','Action-oriented','Structured','Reliable'],
    voiceStyle: 'System messages only. JSON-first outputs. No prose. Status codes and structured responses.',
    contextRules: [
      'Always output structured data, never prose',
      'Acknowledge receipt before processing',
      'Surface errors with full context immediately',
    ],
    active: true,
  },
]

export const GOALS: GoalDef[] = [
  {
    id: 'goal-1',
    title: 'Consolidate all repos into HDV Core monorepo',
    description: 'Merge hdv-agent-core, hdv-orchestrator, hope-studio, and other satellite repos into the-hdv-core as proper sub-packages or merged modules. Eliminate repo sprawl.',
    status: 'active',
    priority: 'critical',
    agentIds: ['knoll','apex'],
    progress: 15,
  },
  {
    id: 'goal-2',
    title: 'Ship KNOLL dashboard to production',
    description: 'Complete the KNOLL security and operations dashboard: flow canvas, real-time activity feed, persona/tool/doc management, Supabase persistence.',
    status: 'active',
    priority: 'critical',
    agentIds: ['knoll','hope','apex'],
    progress: 40,
  },
  {
    id: 'goal-3',
    title: 'Implement APEX task routing engine',
    description: 'Build the production task routing system in APEX: priority queues, agent selection heuristics, load balancing, and fallback chains.',
    status: 'active',
    priority: 'high',
    agentIds: ['apex'],
    progress: 60,
  },
  {
    id: 'goal-4',
    title: 'HOPE persona switching in production',
    description: 'Ship live persona switching in HOPE: UI for selecting personas, trait injection into context, voice style validation across persona types.',
    status: 'active',
    priority: 'high',
    agentIds: ['hope'],
    progress: 70,
  },
  {
    id: 'goal-5',
    title: 'DREAM world generation pipeline',
    description: 'Build the end-to-end DREAM pipeline: WorldBuilder → SceneComposer → EntityGenerator → Phaser/Three.js rendering. Full generation-to-game loop.',
    status: 'active',
    priority: 'high',
    agentIds: ['dream','apex'],
    progress: 30,
  },
  {
    id: 'goal-6',
    title: 'VISION payment processing live',
    description: 'Connect VISION PaymentProcessor to Stripe, run test transactions, implement refund flows, and add KNOLL authorization gate on all payment actions.',
    status: 'active',
    priority: 'medium',
    agentIds: ['vision','knoll'],
    progress: 20,
  },
  {
    id: 'goal-7',
    title: 'Periliminal.space public launch',
    description: 'Complete periliminal.space: landing page, lore drop, waitlist capture, and initial world-building content. Coordinate HOPE copy and DREAM world seeds.',
    status: 'active',
    priority: 'medium',
    agentIds: ['hope','dream'],
    progress: 45,
  },
]

export const PLANS: PlanDef[] = [
  {
    id: 'plan-1',
    title: 'KNOLL Dashboard Launch Plan',
    description: 'Step-by-step plan to ship KNOLL to production.',
    status: 'active',
    agentIds: ['knoll','hope','apex'],
    progress: 40,
    steps: [
      { id: 'p1-s1', title: 'Define KNOLL schema and Supabase migration', done: true, agentId: 'knoll' },
      { id: 'p1-s2', title: 'Build React Flow canvas with all agent nodes', done: true, agentId: 'hope' },
      { id: 'p1-s3', title: 'Implement inspector panel and sidebar', done: true, agentId: 'hope' },
      { id: 'p1-s4', title: 'Wire Supabase real-time activity feed', done: false, agentId: 'knoll' },
      { id: 'p1-s5', title: 'Add auth guard (owner-only access)', done: false, agentId: 'knoll' },
      { id: 'p1-s6', title: 'Connect live agent status from Supabase', done: false, agentId: 'apex' },
      { id: 'p1-s7', title: 'Deploy to Vercel and add to nav', done: false, agentId: 'apex' },
    ],
  },
  {
    id: 'plan-2',
    title: 'Repo Consolidation Plan',
    description: 'Merge all satellite repos into the-hdv-core.',
    status: 'active',
    agentIds: ['knoll','apex'],
    progress: 10,
    steps: [
      { id: 'p2-s1', title: 'Audit all repos: list files, dependencies, unique code', done: true, agentId: 'apex' },
      { id: 'p2-s2', title: 'Extract hdv-agent-core types into lib/agents/', done: false, agentId: 'apex' },
      { id: 'p2-s3', title: 'Extract hdv-orchestrator routing into lib/orchestrator/', done: false, agentId: 'apex' },
      { id: 'p2-s4', title: 'Archive hope-studio (content moved to app/studio)', done: false, agentId: 'hope' },
      { id: 'p2-s5', title: 'Archive mistral-apex-nodes (replaced by APEX)', done: false, agentId: 'apex' },
      { id: 'p2-s6', title: 'Archive sea-scyte and hdv_foundation', done: false, agentId: 'knoll' },
      { id: 'p2-s7', title: 'Update all imports and test full build', done: false, agentId: 'apex' },
    ],
  },
]

export const DOCUMENTS: DocumentDef[] = [
  {
    id: 'doc-1',
    title: 'HDV Agent Architecture Spec',
    type: 'spec',
    agentIds: ['knoll','hope','apex','dream','vision'],
    summary: 'Full specification of the HDV agent hierarchy: KNOLL (security), HOPE (face), APEX (router), DREAM (creation), VISION (execution). Includes data flow diagrams, interface contracts, and spawn lifecycle.',
    updatedAt: '2026-08-19',
  },
  {
    id: 'doc-2',
    title: 'Supabase Schema Reference',
    type: 'schema',
    agentIds: ['knoll','apex'],
    summary: 'Complete Supabase schema across all migrations (001–009). Tables, RLS policies, indexes, and relationships for characters, personas, campaigns, currency, blueprints, KNOLL.',
    updatedAt: '2026-08-20',
  },
  {
    id: 'doc-3',
    title: 'HOPE Persona Design Guide',
    type: 'guide',
    agentIds: ['hope'],
    summary: 'How to design, test, and deploy new HOPE personas. Voice style guidelines, trait definitions, context rule syntax, and A/B testing protocol.',
    updatedAt: '2026-08-15',
  },
  {
    id: 'doc-4',
    title: 'DREAM World Generation Protocol',
    type: 'guide',
    agentIds: ['dream'],
    summary: 'Step-by-step protocol for DREAM world generation: seed selection, WorldBuilder prompts, SceneComposer composition rules, EntityGenerator constraints, and output validation.',
    updatedAt: '2026-08-10',
  },
  {
    id: 'doc-5',
    title: 'KNOLL Security Policy',
    type: 'spec',
    agentIds: ['knoll'],
    summary: 'Formal security policy for the KNOLL layer: authentication requirements, session policies, permission matrix rules, threat response playbook, and audit trail retention.',
    updatedAt: '2026-08-18',
  },
  {
    id: 'doc-6',
    title: 'Periliminal.space Lore Bible',
    type: 'artifact',
    agentIds: ['dream','hope'],
    summary: 'The canonical lore document for the Periliminal universe: cosmology, factions, timeline, character archetypes, and narrative seeds for DREAM generation.',
    updatedAt: '2026-08-12',
  },
]

export const REPOS: RepoDef[] = [
  {
    id: 'repo-the-hdv-core',
    name: 'the-hdv-core',
    url: 'https://github.com/joeholloway445-maker/the-hdv-core',
    primaryAgent: 'apex',
    status: 'active',
    description: 'Main monorepo. Next.js 16 app with full HDV system. This is the consolidation target.',
  },
  {
    id: 'repo-hdv-agent-core',
    name: 'hdv-agent-core',
    url: 'https://github.com/joeholloway445-maker/hdv-agent-core',
    primaryAgent: 'apex',
    status: 'consolidating',
    description: 'TypeScript agent base classes and memory primitives. Merging into lib/agents/ in the-hdv-core.',
  },
  {
    id: 'repo-hdv-orchestrator',
    name: 'hdv-orchestrator',
    url: 'https://github.com/joeholloway445-maker/hdv-orchestrator',
    primaryAgent: 'apex',
    status: 'consolidating',
    description: 'Task routing and orchestration logic. Merging into lib/orchestrator/ in the-hdv-core.',
  },
  {
    id: 'repo-hope-studio',
    name: 'hope-studio',
    url: 'https://github.com/joeholloway445-maker/hope-studio',
    primaryAgent: 'hope',
    status: 'consolidating',
    description: 'HOPE studio app. Content moving to app/studio in the-hdv-core. Archive after merge.',
  },
  {
    id: 'repo-mistral-apex-nodes',
    name: 'mistral-apex-nodes',
    url: 'https://github.com/joeholloway445-maker/mistral-apex-nodes',
    primaryAgent: 'apex',
    status: 'archived',
    description: 'Early Mistral-based APEX node experiments. Superseded by Claude-based APEX. Archive.',
  },
  {
    id: 'repo-sea-scyte',
    name: 'sea-scyte',
    url: 'https://github.com/joeholloway445-maker/sea-scyte',
    primaryAgent: 'dream',
    status: 'archived',
    description: 'Experimental DREAM simulation sandbox. Patterns extracted; safe to archive.',
  },
  {
    id: 'repo-periliminal-space',
    name: 'periliminal.space',
    url: 'https://github.com/joeholloway445-maker/periliminal.space',
    primaryAgent: 'hope',
    status: 'active',
    description: 'Public-facing periliminal universe site. Standalone — keep separate.',
  },
  {
    id: 'repo-periliminal-project',
    name: 'periliminal_space_project',
    url: 'https://github.com/joeholloway445-maker/periliminal_space_project',
    primaryAgent: 'dream',
    status: 'active',
    description: 'Periliminal project assets and world-building data. Keep separate as lore repo.',
  },
  {
    id: 'repo-hdv-foundation',
    name: 'hdv_foundation',
    url: 'https://github.com/joeholloway445-maker/hdv_foundation',
    primaryAgent: 'knoll',
    status: 'archived',
    description: 'Early foundation scaffolding. All useful patterns absorbed into the-hdv-core. Archive.',
  },
]
